apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: rhcl-demo-lan
  namespace: openshift-gitops
spec:
  generators:
    - list:
        elements:
          - name: inventories
            path: app/lan/inventories
            namespace: inventories
          - name: orders
            path: app/lan/orders
            namespace: orders
          - name: rhcl-gateway
            path: gw/lan
            namespace: app-global-lan
  template:
    metadata:
      name: rhcl-{{name}}
    spec:
      project: default
      source:
        repoURL: https://github.com/arencloud/rhcl-demo-lab.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true